import {
  getAvailableStockBriefReviewPairs,
} from "@/lib/data";
import type { RiskGateReview, StockBriefReviewPair } from "@/lib/data";
import { HudMetricCard } from "@/components/HudMetricCard";

export const dynamic = "force-dynamic";
export const fetchCache = "force-no-store";

/** Short label for the risk-gate status card */
function riskGateCardValue(review: RiskGateReview | null): string {
  if (!review?.overall_status) return "—";
  switch (review.overall_status) {
    case "pass":
      return "Pass";
    case "caution":
      return "Caution";
    case "flag":
      return "Flag";
    default:
      return String(review.overall_status);
  }
}

/** One-line plain-English meaning for overall_status */
function riskGateStatusMeaning(status: string | undefined): string {
  switch (status) {
    case "pass":
      return "No major issues were raised in this review.";
    case "caution":
      return "Some concerns were raised and should be checked by a person.";
    case "flag":
      return "A stronger warning was raised and needs human review before moving forward.";
    default:
      return "Unknown status.";
  }
}

function shortDateTime(raw: string | null | undefined): string {
  if (!raw) return "—";
  const s = raw.replace("T", " ").replace("Z", "");
  return s.length > 19 ? s.slice(0, 19) : s;
}

export default async function StockBriefsPage({
  searchParams,
}: {
  searchParams?: { review?: string };
}) {
  const pairs = await getAvailableStockBriefReviewPairs();
  const fallback = pairs[0] ?? null;
  const selectedSuffix = searchParams?.review;
  const selected: StockBriefReviewPair | null =
    (selectedSuffix &&
      pairs.find((p) => p.suffix === selectedSuffix)) ||
    fallback;

  if (!selected || !selected.brief.briefs?.length) {
    return (
      <div className="space-y-6">
        <h2 className="text-xl font-semibold tracking-tight text-cyan-100">
          Stock Brief Review
        </h2>
        <p className="text-sm text-slate-500">
          This page shows Stock Module research brief outputs generated by the
          current manual pipeline. This is a manual review step, not a trading
          decision screen.
        </p>
        <div className="hud-panel p-6">
          <p className="text-amber-400/90">
            No stock brief output found yet.
          </p>
          <p className="mt-2 text-sm text-slate-500">
            Run the research brief first:
          </p>
          <pre className="mt-3 overflow-x-auto rounded bg-slate-900/50 p-3 font-mono text-xs text-slate-300">
            {`cd future_modules/stock_module/scripts
python confirm_watchlist_symbol.py --symbol <SYMBOL>
python run_research_brief.py --packet ../inputs/confirmed_watchlist_packet_<symbol_lower>.json`}
          </pre>
        </div>
      </div>
    );
  }

  const b = selected.brief.briefs[0];
  const symbol = b.symbol ?? "—";
  const confidenceBand = b.confidence_band ?? "—";
  const reviewRec = b.review_recommendation ?? "—";
  const evidenceSources = b.evidence_sources ?? [];
  const openQuestions = b.open_questions ?? [];
  const riskGate = selected.riskGate;
  const hasRiskGate = Boolean(
    riskGate &&
      riskGate.overall_status &&
      ["pass", "caution", "flag"].includes(riskGate.overall_status)
  );
  const flags = riskGate?.flags ?? [];

  return (
    <div className="space-y-6">
      <div className="flex items-end justify-between gap-4 border-b border-cyan-500/20 pb-4">
        <div>
          <h2 className="text-xl font-semibold tracking-tight text-cyan-100">
            Stock Brief Review
          </h2>
          <p className="mt-1 text-sm text-slate-500">
            Selected Stock Module research brief output. Manual review step,
            not a trading decision screen.
          </p>
        </div>
      </div>

      <div className="hud-panel p-4">
        <h3 className="mb-1 text-xs font-medium uppercase tracking-widest text-cyan-400/80">
          Available reviews
        </h3>
        <p className="text-sm text-slate-500">
          Recent stock review files generated by the current manual pipeline.
        </p>

        <p className="mt-2 text-xs text-slate-600">
          The stock brief and risk review currently shown below.
        </p>

        <form method="get" className="mt-3 flex flex-col gap-2 sm:flex-row sm:items-end sm:justify-between">
          <div className="flex flex-col gap-1">
            <label className="text-xs uppercase tracking-wider text-slate-500">
              Selected review
            </label>
            <select
              name="review"
              defaultValue={selected.suffix}
              className="rounded bg-slate-900/50 px-3 py-2 text-sm text-slate-200 ring-1 ring-slate-700/40"
            >
              {pairs.map((p) => (
                <option key={p.suffix} value={p.suffix}>
                  {p.symbol} · {p.confidenceBand ?? "—"} ·{" "}
                  {p.riskGate?.overall_status ?? "Not run yet"} ·{" "}
                  {shortDateTime(p.createdAt)}
                </option>
              ))}
            </select>
          </div>
          <button
            type="submit"
            className="rounded bg-cyan-500/15 px-3 py-2 text-sm font-medium text-cyan-200 ring-1 ring-cyan-500/30 hover:bg-cyan-500/20"
          >
            Show
          </button>
        </form>
      </div>

      <div className="grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-5">
        <HudMetricCard label="Brief files found" value={String(pairs.length)} />
        <HudMetricCard label="Selected symbol reviewed" value={symbol} />
        <div className="hud-metric p-3">
          <div className="text-xs uppercase tracking-wider text-slate-500">
            Confidence band
          </div>
          <div className="mt-1 text-xl font-semibold text-cyan-200">
            {confidenceBand}
          </div>
          <p className="mt-0.5 text-[11px] text-slate-600">
            The model&apos;s rough confidence based on the evidence it used. Not a
            guarantee.
          </p>
        </div>
        <div className="hud-metric p-3">
          <div className="text-xs uppercase tracking-wider text-slate-500">
            Review recommendation
          </div>
          <div className="mt-1 text-xl font-semibold text-cyan-200">
            {reviewRec}
          </div>
          <p className="mt-0.5 text-[11px] text-slate-600">
            Suggested watch posture (e.g. monitor, dig deeper). A person still
            decides the real next move.
          </p>
        </div>
        <div className="hud-metric p-3">
          <div className="text-xs uppercase tracking-wider text-slate-500">
            Risk gate status
          </div>
          <div className="mt-1 text-xl font-semibold text-cyan-200">
            {hasRiskGate ? riskGateCardValue(riskGate) : "Not run yet"}
          </div>
          <p className="mt-0.5 text-[11px] text-slate-600">
            A simple review result based on the brief. This is advisory only.
          </p>
        </div>
      </div>

      <p className="text-xs text-slate-500">
        <span className="font-medium text-slate-400">Risk gate terms:</span>{" "}
        <strong className="text-slate-400">Pass</strong> — no major issues were
        raised in this review. <strong className="text-slate-400">Caution</strong>{" "}
        — some concerns were raised and should be checked by a person.{" "}
        <strong className="text-slate-400">Flag</strong> — a stronger warning was
        raised and needs human review before moving forward.
      </p>

      {!hasRiskGate && (
        <div className="hud-panel p-4">
          <h3 className="mb-1 text-xs font-medium uppercase tracking-widest text-amber-400/80">
            Risk gate review
          </h3>
          <p className="text-sm text-slate-300">
            No risk gate file was found for the selected research brief. This
            page looks for a file whose name matches the brief: same suffix after{" "}
            <code className="rounded bg-slate-900/60 px-1 font-mono text-xs">
              stock_research_brief_
            </code>{" "}
            and{" "}
            <code className="rounded bg-slate-900/60 px-1 font-mono text-xs">
              risk_gate_review_
            </code>
            .
          </p>
          <p className="mt-2 text-sm text-slate-500">
            Run the risk gate step manually (not automated, not trade execution):
          </p>
          <pre className="mt-2 overflow-x-auto rounded bg-slate-900/50 p-3 font-mono text-xs text-slate-300">
            {(() => {
              const briefFileName =
                selected.briefPath.split(/[/\\]/).pop() ?? selected.briefPath;
              return `cd future_modules/stock_module/scripts
python run_risk_gate.py --brief ../outputs/${briefFileName}`;
            })()}
          </pre>
          <p className="mt-2 text-[11px] text-slate-600">
            Use the same filename stem as your selected brief: after{" "}
            <code className="font-mono">stock_research_brief_</code>, the risk file
            must be{" "}
            <code className="font-mono">risk_gate_review_</code> + that stem +
            <code className="font-mono">.json</code>.
          </p>
        </div>
      )}

      {hasRiskGate && riskGate && (
        <div className="hud-panel p-4">
          <h3 className="mb-1 text-xs font-medium uppercase tracking-widest text-cyan-400/80">
            Risk gate review
          </h3>
          <p className="mb-3 text-xs text-slate-500">
            Advisory check on the brief below. Not an automated decision and not
            trade execution.
          </p>
          <div className="space-y-4">
            <div>
              <div className="text-xs text-slate-500">Overall status</div>
              <p className="mt-1 font-medium text-cyan-200">
                {riskGate.overall_status}
              </p>
              <p className="mt-0.5 text-sm text-slate-400">
                {riskGateStatusMeaning(riskGate.overall_status)}
              </p>
            </div>
            {riskGate.summary && (
              <div>
                <div className="text-xs text-slate-500">Summary</div>
                <p className="mt-1 text-sm text-slate-300">{riskGate.summary}</p>
              </div>
            )}
            <div>
              <div className="text-xs text-slate-500">Flags</div>
              <p className="mt-0.5 text-[11px] text-slate-600">
                Specific concerns the review identified.
              </p>
              {flags.length === 0 ? (
                <p className="mt-1 text-sm text-slate-400">
                  No risk flags were raised in this review.
                </p>
              ) : (
                <ul className="mt-2 space-y-2">
                  {flags.map((f, i) => (
                    <li
                      key={i}
                      className="rounded border border-slate-700/40 bg-slate-900/30 px-3 py-2 text-sm text-slate-300"
                    >
                      <span className="font-mono text-cyan-200/90">
                        {f.symbol}
                      </span>
                      <span className="text-slate-500"> · </span>
                      <span className="text-slate-400">{f.rule}</span>
                      <p className="mt-1 text-slate-400">{f.description}</p>
                    </li>
                  ))}
                </ul>
              )}
            </div>
          </div>
        </div>
      )}

      <div className="hud-panel p-4">
        <h3 className="mb-1 text-xs font-medium uppercase tracking-widest text-cyan-400/80">
          Brief summary
        </h3>
        <div className="space-y-4">
          <div>
            <div className="text-xs text-slate-500">Symbol</div>
            <p className="mt-1 font-mono text-cyan-200">{symbol}</p>
          </div>
          {b.thesis_or_watch_reason && (
            <div>
              <div className="text-xs text-slate-500">
                Why it is on the watchlist
              </div>
              <p className="mt-1 text-sm text-slate-300">
                {b.thesis_or_watch_reason}
              </p>
            </div>
          )}
          {b.catalyst_summary && (
            <div>
              <div className="text-xs text-slate-500">Main catalysts</div>
              <p className="mt-0.5 text-[11px] text-slate-600">
                Events or conditions that could help move the stock.
              </p>
              <p className="mt-1 text-sm text-slate-300">
                {b.catalyst_summary}
              </p>
            </div>
          )}
          {b.risk_summary && (
            <div>
              <div className="text-xs text-slate-500">Main risks</div>
              <p className="mt-1 text-sm text-slate-300">{b.risk_summary}</p>
            </div>
          )}
          {openQuestions.length > 0 && (
            <div>
              <div className="text-xs text-slate-500">Open questions</div>
              <p className="mt-0.5 text-[11px] text-slate-600">
                Important unknowns to check before acting.
              </p>
              <ul className="mt-1 list-inside list-disc space-y-0.5 text-sm text-slate-300">
                {openQuestions.map((q, i) => (
                  <li key={i}>{q}</li>
                ))}
              </ul>
            </div>
          )}
          {reviewRec && reviewRec !== "—" && (
            <div>
              <div className="text-xs text-slate-500">Suggested next posture</div>
              <p className="mt-1 text-sm text-cyan-200">{reviewRec}</p>
            </div>
          )}
        </div>
      </div>

      {evidenceSources.length > 0 && (
        <div className="hud-panel p-4">
          <h3 className="mb-1 text-xs font-medium uppercase tracking-widest text-cyan-400/80">
            Evidence used
          </h3>
          <p className="mb-3 text-xs text-slate-500">
            Sources referenced in the brief. Titles and dates as provided by the
            model.
          </p>
          <div className="space-y-2">
            {evidenceSources.map((src, i) => (
              <div
                key={i}
                className="flex flex-wrap items-baseline gap-2 rounded border border-slate-700/40 bg-slate-900/30 px-3 py-2 text-sm"
              >
                <span className="font-medium text-slate-400">
                  {src.type ?? "source"}
                </span>
                <span className="text-slate-300">{src.title ?? "—"}</span>
                {src.date && (
                  <span className="text-xs text-slate-600">{src.date}</span>
                )}
              </div>
            ))}
          </div>
        </div>
      )}

      <div className="rounded border border-amber-500/30 bg-amber-500/10 p-4">
        <h3 className="text-sm font-medium text-amber-400/90">
          Manual review required
        </h3>
        <p className="mt-1 text-sm text-slate-300">
          This brief and any risk gate output were generated for operator review.
          Nothing here executes trades or places orders. It is not real-time
          market data. A person still decides every next step.
        </p>
      </div>
    </div>
  );
}
