"""
Build an operator-facing daily execution prep package by chaining existing helpers.
Read-only with respect to backlog/state; writes prep markdown and helper outputs only.
"""
from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Prepare a daily execution prep package by chaining selection, handoff, and summary helpers. "
            "Does not execute tasks or mutate backlog/state."
        )
    )
    parser.add_argument(
        "--workspace",
        help="Jarvis workspace root (default: parent of scripts/).",
    )
    parser.add_argument(
        "--project",
        default="WCS",
        help="Project filter for automatic selection (default: WCS).",
    )
    parser.add_argument(
        "--task",
        help="Task id to use directly (e.g. WCS-019). If omitted, select via select_next_ready_task.py.",
    )
    parser.add_argument(
        "--output",
        help=(
            "Output prep file path. Default: "
            "scratch/daily_execution_prep/<task>_daily_execution_prep.md"
        ),
    )
    return parser.parse_args()


def normalize_task_id(raw: str) -> str:
    t = raw.strip().upper()
    if not re.match(r"^WCS-\d+$", t):
        raise ValueError(f"Task id must match WCS-NNN. Got: {raw!r}")
    return t


def run_helper(
    name: str,
    cmd: List[str],
    cwd: Path,
) -> Tuple[int, str]:
    proc = subprocess.run(
        cmd,
        cwd=str(cwd),
        capture_output=True,
        text=True,
    )
    out = (proc.stdout or "").strip()
    if proc.stderr:
        out = out + "\n" + proc.stderr.strip() if out else proc.stderr.strip()
    return proc.returncode, out


def select_task_via_helper(workspace: Path, project: str) -> Tuple[Optional[str], int, str]:
    """
    Run select_next_ready_task.py; return (task_id_or_none, exit_code, output).
    """
    scripts_dir = workspace / "scripts"
    cmd = [
        sys.executable,
        str(scripts_dir / "select_next_ready_task.py"),
        "--workspace",
        str(workspace),
        "--project",
        project,
    ]
    code, out = run_helper("select_next_ready_task", cmd, workspace)
    task_id = None
    if code == 0:
        for line in out.splitlines():
            line = line.strip()
            if line.startswith("Selected task id:"):
                task_id = line.split(":", 1)[1].strip().upper()
                break
    return task_id, code, out


def build_prep_content(
    task_id: str,
    title: str,
    project: str,
    expected_branch: str,
    current_branch: Optional[str],
    handoff_path: Path,
    summary_path: Path,
) -> str:
    current_branch_line = current_branch if current_branch else "(unable to resolve — check repo)"
    lines = [
        f"# Daily execution prep: {task_id}",
        "",
        f"- **Task ID:** {task_id}",
        f"- **Title:** {title or '(see task packet)'}",
        f"- **Project:** {project}",
        f"- **Expected branch:** {expected_branch}",
        f"- **Current branch:** {current_branch_line}",
        "",
        "## Generated artifacts",
        f"- **Cursor handoff:** {handoff_path}",
        f"- **Task-cycle summary:** {summary_path}",
        "",
        "## Next action",
        "1. Open the Cursor handoff file and use it as the copy/paste prompt for implementation.",
        "2. After worker implementation and commit, run post-worker guards and QA as per the task cycle.",
        "3. Use the task-cycle summary to confirm evidence and next steps.",
        "",
        "---",
        "",
        "*This prep was generated by build_daily_execution_prep.py. It prepares execution but does not execute tasks or mutate backlog/state.*",
        "",
    ]
    return "\n".join(lines)


def read_json(path: Path) -> Any:
    return json.loads(path.read_text(encoding="utf-8"))


def get_repo_path(workspace: Path) -> Optional[Path]:
    state_file = workspace / "state" / "project_status_wcs.json"
    if not state_file.is_file():
        return None
    try:
        data = read_json(state_file)
        return Path(data.get("repo_path", "")).resolve() if data.get("repo_path") else None
    except Exception:
        return None


def get_current_branch(repo_path: Path) -> Optional[str]:
    try:
        r = subprocess.run(
            ["git", "branch", "--show-current"],
            cwd=repo_path,
            capture_output=True,
            text=True,
            timeout=5,
        )
        if r.returncode == 0 and r.stdout:
            return r.stdout.strip()
    except Exception:
        pass
    return None


def main() -> int:
    args = parse_args()
    workspace = Path(args.workspace).resolve() if args.workspace else Path(__file__).resolve().parent.parent
    project = (args.project or "WCS").strip()
    task_arg = args.task.strip() if args.task else None

    if not workspace.exists():
        print("DAILY EXECUTION PREP: FAIL")
        print(f"Workspace: {workspace}")
        print(f"Project: {project}")
        print("Failed step: (validation)")
        print("Reason: Workspace path does not exist.")
        return 1

    task_id: Optional[str] = None
    task_supplied = False

    if task_arg:
        try:
            task_id = normalize_task_id(task_arg)
            task_supplied = True
        except ValueError as e:
            print("DAILY EXECUTION PREP: FAIL")
            print(f"Workspace: {workspace}")
            print(f"Project: {project}")
            print("Failed step: (validation)")
            print(f"Reason: {e}")
            return 1
    else:
        task_id, sel_code, sel_out = select_task_via_helper(workspace, project)
        if sel_code == 2:
            print("DAILY EXECUTION PREP: FAIL")
            print(f"Workspace: {workspace}")
            print(f"Project: {project}")
            print("Failed step: select_next_ready_task")
            print("Reason: No eligible task found (NO MATCH).")
            return 2
        if sel_code != 0 or not task_id:
            print("DAILY EXECUTION PREP: FAIL")
            print(f"Workspace: {workspace}")
            print(f"Project: {project}")
            print("Failed step: select_next_ready_task")
            print("Failed command: select_next_ready_task.py --workspace ... --project ...")
            print(f"Reason: Selection failed (exit {sel_code}) or could not parse selected task id.")
            return 1

    scripts_dir = workspace / "scripts"

    # Build handoff
    handoff_cmd = [
        sys.executable,
        str(scripts_dir / "build_cursor_handoff.py"),
        "--task",
        task_id,
        "--workspace",
        str(workspace),
    ]
    h_code, h_out = run_helper("build_cursor_handoff", handoff_cmd, workspace)
    if h_code != 0:
        print("DAILY EXECUTION PREP: FAIL")
        print(f"Workspace: {workspace}")
        print(f"Project: {project}")
        print("Failed step: build_cursor_handoff")
        print(f"Failed command: {' '.join(handoff_cmd)}")
        print(f"Reason: Handoff build failed (exit {h_code}).")
        return 1

    # Default handoff path
    handoff_path = workspace / "scratch" / "cursor_handoffs" / f"{task_id}_cursor_handoff.md"

    # Build task-cycle summary
    summary_cmd = [
        sys.executable,
        str(scripts_dir / "build_task_cycle_summary.py"),
        "--task",
        task_id,
        "--workspace",
        str(workspace),
    ]
    s_code, s_out = run_helper("build_task_cycle_summary", summary_cmd, workspace)
    if s_code != 0:
        print("DAILY EXECUTION PREP: FAIL")
        print(f"Workspace: {workspace}")
        print(f"Project: {project}")
        print("Failed step: build_task_cycle_summary")
        print(f"Failed command: {' '.join(summary_cmd)}")
        print(f"Reason: Task-cycle summary build failed (exit {s_code}).")
        return 1

    summary_path = workspace / "scratch" / "task_cycle_summaries" / f"{task_id}_task_cycle_summary.md"

    # Resolve title and branch for prep file
    packet_path = workspace / "tasks" / f"{task_id}_task.json"
    title = ""
    if packet_path.is_file():
        try:
            packet = read_json(packet_path)
            if isinstance(packet, dict):
                title = (packet.get("title") or packet.get("task_id") or "").strip()
        except Exception:
            pass
    expected_branch = f"jarvis-task-{task_id.lower()}"
    repo_path = get_repo_path(workspace)
    current_branch = get_current_branch(repo_path) if repo_path and repo_path.exists() else None

    # Output prep file
    if args.output:
        prep_path = Path(args.output).resolve()
    else:
        prep_dir = workspace / "scratch" / "daily_execution_prep"
        prep_dir.mkdir(parents=True, exist_ok=True)
        prep_path = prep_dir / f"{task_id}_daily_execution_prep.md"

    content = build_prep_content(
        task_id=task_id,
        title=title,
        project=project,
        expected_branch=expected_branch,
        current_branch=current_branch,
        handoff_path=handoff_path,
        summary_path=summary_path,
    )
    try:
        prep_path.parent.mkdir(parents=True, exist_ok=True)
        prep_path.write_text(content, encoding="utf-8")
    except Exception as e:
        print("DAILY EXECUTION PREP: FAIL")
        print(f"Workspace: {workspace}")
        print(f"Project: {project}")
        print("Failed step: write prep file")
        print(f"Reason: Could not write prep file: {e}")
        return 1

    print("DAILY EXECUTION PREP: PASS")
    print(f"Workspace: {workspace}")
    print(f"Project: {project}")
    print(f"Selected task id: {task_id}")
    print(f"Output prep file: {prep_path}")
    print(f"Handoff file: {handoff_path}")
    print(f"Task-cycle summary: {summary_path}")
    print(f"Task selection: {'supplied explicitly (--task)' if task_supplied else 'automatic (select_next_ready_task)'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
